### ISSUE TITLE
Add a few blog posts and papers

### ISSUE THREAD

**Issue by patrickmineault** [CYHSM/awesome-neuro-ai-papers#2]
Not to toot my own horn, but a couple of blog posts I wrote are relevant:

* https://xcorr.net/2021/12/31/2021-in-review-unsupervised-brain-models/ (and also references therein)
* https://xcorr.net/2022/05/18/whats-the-endgame-of-neuroai/

Here's a recent pop-sci article in quanta that's quite good:

* https://twitter.com/anilananth/status/1557776303993958400

**Comment by CYHSM** [comment]
Yes of course, sorry I forgot to add these when they came out. I have added your posts to the Blogs section, will check out the quanta article now. 
Edit: Added the quanta article and some additional papers from it, thanks again!
